### ISSUE TITLE
Android app implementation

### ISSUE THREAD

**Issue by larrywal-express** [doleron/yolov5-opencv-cpp-python#1]
Thanks for your good.. how to implement the opencv on Android app.?

**Comment by doleron** [comment]
Hi, @larrywal-express, Thanks! Particularly, I have no background on Android/mobile development. Thus, I don't know how to precisely answer your question. I have seen people using C++ and Java for build their computer vision projects for smartphones. I think it is not that hard to do. Sorry, if I realize how to make it, I hit you here.

**Comment by doleron** [comment]
@hjw520365 No friend, I have any idea what is happen in your code. Maybe a problem with your ONNX file.

**Comment by hjw520365** [comment]
Thank you for your reply. But, I can run use Python with the onnx file.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Thu, Jan 20, 2022 21:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [doleron/yolov5-opencv-cpp-python] Android app implementation(Issue #1)




 
@hjw520365 No friend, I have any idea what is happen in your code. Maybe a problem with your ONNX file.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hjw520365** [comment]
> @hjw520365 No friend, I have any idea what is happen in your code. Maybe a problem with your ONNX file.
Thank you! That's the problem, and do you know how to create correct ONNX file? Or how to  modify the code?

**Comment by doleron** [comment]
Sorry friend I cannot support you on your code. I'm closing this issue.
