### ISSUE TITLE
file too short error

### ISSUE THREAD

**Issue by dwight-foster** [doleron/yolov5-opencv-cpp-python#11]
Hello I keep getting this error:
./yolo_example: error while loading shared libraries: /home/dwight/intel/openvino_2022/runtime/3rdparty/tbb/lib/libtbb.so: file too short
I am following the correct steps for running this repo and I have reinstalled openvino multiple times but keep getting the same error. I have changed nothing else. Any help would be appreciated thank you.

**Comment by doleron** [comment]
Sorry bro, it seems that you are getting some environment issue which is beyond the scope of this repo. I suggest perform a clean install of OpenCV on a linux machine and try it again.
