### ISSUE TITLE
Fail to run the yolo_example

### ISSUE THREAD

**Issue by lanbao2021** [doleron/yolov5-opencv-cpp-python#2]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/77654725/150519862-0361f545-49fc-46e4-a560-070e5a5f36f8.png">

OpenCV 4.5.4 was installed

@doleron I need help🤕

**Comment by doleron** [comment]
Hi @lanbao2021 it seems that your pip opencv version are being used instead of your system opencv. You can:
- try removing/uninstall opencv from pip
- upgrade the opencv version in pip
I'm closing this issues since it is related to system setup.
