### ISSUE TITLE
on windows 11

### ISSUE THREAD

**Issue by manuelddahmen** [doleron/yolov5-opencv-cpp-python#5]
it works very well on windows too.
just need to change cv2 to opencv-python

would it be possible to grab a  live camera instead of mp4 files?

**Comment by doleron** [comment]
For webcam you may try:

```python
def load_capture():
    capture = cv2.VideoCapture(0)
    return capture
```
or
```python
def load_capture():
    capture = cv2.VideoCapture(1)
    return capture
```

see https://docs.opencv.org/4.x/dd/d43/tutorial_py_video_display.html
