### ISSUE TITLE
the vsion of yolov5 ?

### ISSUE THREAD

**Issue by GaoJieo** [doleron/yolov5-opencv-cpp-python#6]
Hi, doleron.
Could you tell me which version of yoloV5 you use? 
 I modified data+=7, using custom weight still error.
![error](https://user-images.githubusercontent.com/81306668/158769433-1ed24e6f-4382-47ba-a7bf-0537ae4f044a.jpg)

hope to your reply.

**Comment by GaoJieo** [comment]
Eventually the code runs out, but all the labels are in the upper left corner.

**Comment by GaoJieo** [comment]
Thank you for your reply. 
I'm using yolov5 v5.0.
Running programs are stuck on Ubuntu.
The code also worked on Windows, so I used VS debugging and found data[4] exceptions.  
![image](https://user-images.githubusercontent.com/81306668/159103793-1daabef6-174b-4973-b501-1386791f26d4.png)

**Comment by GaoJieo** [comment]
I used yolov5-6.1 to export the ONNX model and it worked successfully. (And yolov5n.pt is so fast )
I don't know why.  
![image](https://user-images.githubusercontent.com/81306668/159146400-7d3ac828-c773-4e84-8a66-ccbae3a11601.png)

**Comment by GaoJieo** [comment]
I found this reason.
The ONNX model output exported by YoloV5-5.0 consists of three output layers.
it's my fault.
![image](https://user-images.githubusercontent.com/81306668/160322175-a0cb94f5-b2b8-41de-8c66-b8d3303ce908.png)

**Comment by feelingsa** [comment]
老哥可以分享下6.1版本的annox文件吗？刚入坑....

**Comment by GaoJieo** [comment]
啥annox文件？是yolox吗？太久了，不是很清楚，你可以看看我写的这篇博客，是关于这个项目的https://blog.csdn.net/weixin_46596757/article/details/123409536



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月4日(星期天) 凌晨1:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [doleron/yolov5-opencv-cpp-python] the vsion of yolov5 ? (Issue #6)





 
老哥可以分享下6.1版本的annox文件吗？刚入坑....
